[opener]
pdf_viewer = [
{
    run = 'zathura "$@"', orphan = true, desc = "zathura"
  }
]
[open]
prepend_rules = [
{ mime = "application/pdf", use = "pdf_viewer"}
]

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
